export const vehicles = [
  {
    slug: "renault-zoe-life-2016",
    brand: "Renault",
    model: "ZOE Life",
    condition: "Gebraucht",
    price: 9000,
    mileage: 85000,
    firstRegistration: "2016-11",
    power: { kw: 43, ps: 58 },
    fuel: "Elektro",
    transmission: "Automatik",
    location: "Kallmünz",
    image: "/images/fahrzeuge/zoe-life-2016.jpg",
    badge: null,
  },
  {
    slug: "renault-clio-evolution-2026",
    brand: "Renault",
    model: "Clio Evolution",
    condition: "Neu",
    price: 22699,
    mileage: 10,
    firstRegistration: null,
    power: { kw: 67, ps: 91 },
    fuel: "Benzin",
    transmission: "Schaltgetriebe",
    location: "Kallmünz",
    image: "/images/fahrzeuge/clio-evolution-2026.jpg",
    badge: "NEU",
  },
  {
    slug: "dacia-spring-comfort-plus-2022",
    brand: "Dacia",
    model: "Spring Comfort Plus",
    condition: "Gebraucht",
    price: 11500,
    mileage: 17347,
    firstRegistration: "2022-08",
    power: { kw: 33, ps: 45 },
    fuel: "Elektro",
    transmission: "Automatik",
    location: "Kallmünz",
    image: "/images/fahrzeuge/dacia-spring-2022.jpg",
    badge: null,
  },
  {
    slug: "renault-zoe-experience-2020",
    brand: "Renault",
    model: "ZOE Experience",
    condition: "Gebraucht",
    price: 14500,
    priceIncludesVAT: true,
    mileage: 38205,
    firstRegistration: "2020-12",
    power: { kw: 51, ps: 69 },
    fuel: "Elektro",
    transmission: "Automatik",
    location: "Kallmünz",
    image: "/images/fahrzeuge/zoe-experience-2020.jpg",
    badge: null,
  },
];
